version: '2.2'

services:
  db:
    build: .
    ports:
      - "6432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  debug:
    image: quay.io/giantswarm/debug
    entrypoint: bash -c "sleep 50000"

  web:
    #build: ../sensordb
    image: geocryology/sensordb:latest
    entrypoint: bash -c "for i in 1 2 3 4 5; do sensorDb run && break || sleep 30; done"
    volumes:
      - ./sensordb-config:/opt/sensorDb/config
    ports:
      - "5308:5308"
    depends_on:
      - db

volumes:
  db-data: