CREATE ROLE observations_read WITH
  NOLOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION;

CREATE ROLE observations_write WITH
  NOLOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION;

--ACCESS DB
-- REVOKE CONNECT ON DATABASE observations FROM PUBLIC;
GRANT  CONNECT ON DATABASE observations  TO observations_write;
GRANT  CONNECT ON DATABASE observations  TO observations_read;

--ACCESS SCHEMA
-- REVOKE ALL     ON SCHEMA public FROM PUBLIC;
GRANT  USAGE   ON SCHEMA public  TO observations_write;
GRANT  USAGE   ON SCHEMA public  TO observations_read;

--ACCESS TABLES
-- REVOKE ALL ON ALL TABLES IN SCHEMA public FROM PUBLIC ;
GRANT SELECT                         ON ALL TABLES IN SCHEMA public TO observations_read ;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO observations_write;

CREATE ROLE sensordb WITH LOGIN PASSWORD 'sdbpassword';

\connect observations

GRANT CONNECT ON DATABASE observations TO sensordb;
GRANT USAGE ON SCHEMA public TO sensordb;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO sensordb;
GRANT ALL PRIVILEGES  ON ALL TABLES IN SCHEMA public TO sensordb;


